version: '3'

services:
  db:
    image: zhangpn/postgres
  web:
    build: docker
    volumes:
      - .:/project/optrak
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["/project/optrak/docker/wait-for-db.sh", "db:5432", "--", "/project/optrak/docker/run-python.sh"]
