# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugId', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('days', models.IntegerField(default=0)),
                ('dateWritten', models.DateField(null=True)),
                ('dateFilled', models.DateField(null=True)),
                ('rxNumber', models.IntegerField(default=0)),
                ('refills', models.IntegerField(default=0)),
            ],
        ),
    ]
